version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    container_name: nebulashare-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nebuladb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: manikantayamala/nebulashare-backend:v1
    container_name: nebulashare-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/nebuladb?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: yamala

  frontend:
    image: manikantayamala/nebulashare-frontend:v1
    container_name: nebulashare-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
