apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebulashare-frontend
spec:
  selector:
    matchLabels:
      app: nebulashare-frontend
  template:
    metadata:
      labels:
        app: nebulashare-frontend
    spec:
      containers:
        - name: nebulashare-frontend
          image: manikantayamala/nebulashare-frontend:v2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nebulashare-frontend
spec:
  selector:
    app: nebulashare-frontend
  ports:
    - port: 3000
      targetPort: 80
  type: NodePort
